spring:
  security:
    saml2:
      relyingparty:
        registration:
          wso2:
            assertingparty:
              metadata-uri: {aurora metadata url}
            signing:
              credentials:
                - private-key-location: {your application private key}
                  certificate-location: {your application cert}
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
